update pipeline

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -30,6 +30,7 @@ jobs:
 
     - name: Upload Test Results
       uses: actions/upload-artifact@v4
+      if: success() || failure()
       with:
         name: ${{ env.TEST_RESULTS_ARTIFACT }}
         path: ${{ env.TEST_RESULTS_FILE }}
@@ -44,13 +45,8 @@ jobs:
         reportType: 'junit'
         access-token: ${{secrets.GITHUB_TOKEN}}
 
-    - name: MirageNet NUnit Reporter
-      uses: MirageNet/nunit-reporter@v1.1.0
-      if: success() || failure()
-      with:
-        path: ${{ env.TEST_RESULTS_FILE }}
-        reportTitle: "MirageNet NUnit Reporter"
-        access-token: ${{ secrets.GITHUB_TOKEN }}
+    - name: After Hyland Reporter
+      run: echo "This should not run after Hyland Reporter sees a test failure."
 
     - name: Dorny Test Reporter
       uses: dorny/test-reporter@v1
@@ -62,3 +58,6 @@ jobs:
         reporter: 'java-junit'
         fail-on-error: 'true'
         fail-on-empty: 'true'
+
+    - name: After All
+      run: echo "This should only run after all tests have passed."
